---
# file: roles/corosync/tasks/auth.yml
- name: Checking if /etc/corosync/authkey exists
  stat:
    path=/etc/corosync/authkey
  register: authkey_file

- name: Generating /eyc/corosync/authkey file
  command: /usr/sbin/corosync-keygen
  run_once: true
  when: authkey_file.stat.exists == False

- name: Waiting for /etc/corosync/authkey file
  wait_for:
    path=/etc/corosync/authkey
    timeout=30
  when: inventory_hostname == play_hosts[0]

- name: Fetching /etc/corosync/authkey to /tmp
  fetch:
    src=/etc/corosync/authkey
    dest=/tmp/
    flat=yes
  when: inventory_hostname == play_hosts[0]

- name: Synchronizing /etc/corosync/authkey everywhere
  copy:
    src=/tmp/authkey
    dest=/etc/corosync/authkey
    mode=0400
  when: inventory_hostname != play_hosts[0]
