---
# file: roles/corosync/tasks/auth.yml
- name: Check if /etc/corosync/authkey exists
  stat:
    path=/etc/corosync/authkey
  register: authkey_file
  tags:
    - corosync
    - corosync-keygen

- name: Generate authkey file
  command: /usr/sbin/corosync-keygen
  when: authkey_file.stat.exists == False and inventory_hostname == master
  tags:
    - corosync
    - corosync-keygen

- name: Wait for /etc/corosync/authkey file
  wait_for:
    path=/etc/corosync/authkey
    timeout=30
  when: inventory_hostname == master
  tags:
    - corosync
    - corosync-keygen

- name: Fetch /etc/corosync/authkey to /tmp
  fetch: src=/etc/corosync/authkey dest=/tmp/ flat=yes
  when: authkey_file.stat.exists == True and inventory_hostname == master
  tags:
    - corosync
    - corosync-keygen

- name: Synchronize authkey file everywhere
  copy: src=/tmp/authkey dest=/etc/corosync/authkey
    owner=root
    group=root
    mode=0400
  tags:
    - corosync
    - corosync-keygen
